# Generated by Django 4.0.4 on 2024-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.FileField(blank=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
