# Generated by Django 4.0.4 on 2024-03-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='profileImage',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
