# Generated by Django 4.0.4 on 2024-03-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_profileimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='altBackgroundImage',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
