# Generated by Django 4.0.4 on 2024-03-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_home_altbackgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
