# Generated by Django 4.0.4 on 2024-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_home_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
