# Generated by Django 4.0.4 on 2024-03-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='research',
            field=models.TextField(blank=True),
        ),
    ]
