# Generated by Django 4.0.4 on 2024-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=300)),
                ('pdf', models.FileField(blank=True, upload_to='assets/papers/')),
                ('images', models.ManyToManyField(blank=True, related_name='+', to='home.image')),
            ],
        ),
    ]
