# Generated by Django 4.0.4 on 2024-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_research_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='collaborators',
            field=models.TextField(blank=True),
        ),
    ]
