# Generated by Django 4.0.4 on 2024-03-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_research_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
