# Generated by Django 4.0.4 on 2024-03-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_research_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='dateStr',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='research',
            name='date',
            field=models.DateField(blank=True, max_length=300, null=True),
        ),
    ]
