# Generated by Django 4.0.4 on 2024-03-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_research_datestr_alter_research_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='abstract',
            field=models.TextField(blank=True),
        ),
    ]
