# Generated by Django 4.0.4 on 2024-03-13 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
