# Generated by Django 4.0.4 on 2024-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_email_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='keywords',
            field=models.TextField(blank=True),
        ),
    ]
