# Generated by Django 4.0.4 on 2024-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_research_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('mame', models.CharField(blank=True, max_length=300)),
                ('message', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
