# Generated by Django 4.0.4 on 2024-03-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_usercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercontact',
            old_name='mame',
            new_name='name',
        ),
    ]
